"use client";

import { DollarSign, TrendingUp, BadgePoundSterling } from "lucide-react";
import { useAnalysisStore } from "@/lib/store/analysisStore";

export default function FinancialCard() {
  const { analysis } = useAnalysisStore();

  if (!analysis) return null;

  return (
    <section className="space-y-8">

      <div>

        <p className="text-sm font-semibold uppercase tracking-widest text-green-600">
          Financial Outlook
        </p>

        <h2 className="mt-2 text-3xl font-bold">
          Business Financial Analysis
        </h2>

        <p className="mt-3 text-gray-500">
          High-level commercial evaluation generated by Atlas AI.
        </p>

      </div>

      <div className="grid gap-6 lg:grid-cols-3">

        <div className="rounded-3xl border border-gray-200 bg-white p-7 shadow-sm">

          <div className="mb-5 flex items-center gap-3">

            <div className="rounded-2xl bg-green-100 p-3">

              <DollarSign className="h-6 w-6 text-green-600" />

            </div>

            <h3 className="text-xl font-bold">
              Revenue Model
            </h3>

          </div>

          <p className="leading-8 text-gray-700">
            {analysis.business_model}
          </p>

        </div>

        <div className="rounded-3xl border border-gray-200 bg-white p-7 shadow-sm">

          <div className="mb-5 flex items-center gap-3">

            <div className="rounded-2xl bg-blue-100 p-3">

              <TrendingUp className="h-6 w-6 text-blue-600" />

            </div>

            <h3 className="text-xl font-bold">
              Market Potential
            </h3>

          </div>

          <p className="leading-8 text-gray-700">
            {analysis.market_size}
          </p>

        </div>

        <div className="rounded-3xl border border-gray-200 bg-white p-7 shadow-sm">

          <div className="mb-5 flex items-center gap-3">

            <div className="rounded-2xl bg-purple-100 p-3">

              <BadgePoundSterling className="h-6 w-6 text-purple-600" />

            </div>

            <h3 className="text-xl font-bold">
              Investment Score
            </h3>

          </div>

          <div className="mt-2 flex items-end gap-2">

            <span className="text-6xl font-extrabold text-gray-900">
              {analysis.score}
            </span>

            <span className="mb-2 text-gray-500">
              /100
            </span>

          </div>

          <p className="mt-4 text-gray-500">
            Overall startup investment potential generated by Atlas AI.
          </p>

        </div>

      </div>

      <div className="rounded-3xl bg-gradient-to-r from-emerald-600 to-green-700 p-8 text-white shadow-xl">

        <h3 className="text-2xl font-bold">
          Financial Recommendation
        </h3>

        <p className="mt-4 leading-8 text-green-100">
          Focus on validating revenue with a small group of paying customers
          before investing heavily in scaling. Prioritize predictable recurring
          revenue and measurable unit economics.
        </p>

      </div>

    </section>
  );
}