import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { ToastProvider, ToastViewport, ToastList } from "@/components/ui/toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* A real crash, reproduced live during Milestone 45's own
            end-to-end verification: a browser auto-translating this page
            (Chrome's built-in Translate, common for any visitor whose
            browser locale differs from "en") mutates the live DOM out
            from under React's own reconciliation, throwing a genuine
            "NotFoundError: Failed to execute 'insertBefore'" that trips
            the route's error boundary mid-analysis. This tells Google
            Translate not to offer translation on this page at all —
            the standard, documented fix for this exact conflict. */}
        <meta name="google" content="notranslate" />
        {/* Applies the saved theme before first paint, so there's no
            flash of the wrong theme. See CLAUDE.md Section 10 / 9 — the
            .dark class this toggles is the same one globals.css already
            defines tokens for. suppressHydrationWarning on <html> above
            is required since this script edits the DOM before React
            hydrates.
            Uses next/script's beforeInteractive strategy rather than a
            raw <script> tag — a plain JSX <script> isn't managed by
            Next.js's script pipeline, so React can end up recreating it
            via the DOM API on reconciliation, and script elements built
            that way are not guaranteed to execute. beforeInteractive is
            the strategy Next.js documents for exactly this "run before
            hydration" use case, and it's only valid in the root layout,
            which this is. */}
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("atlas-ai-theme");var isDark=t?t==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches;if(isDark)document.documentElement.classList.add("dark")}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {/* Wraps the whole app once (Milestone 45) so any client
            component can call useToastManager().add(...) without its
            own provider — matching the "one shared mechanism" rule
            already applied to Zustand for shared state. */}
        <ToastProvider>
          {children}
          <ToastViewport>
            <ToastList />
          </ToastViewport>
        </ToastProvider>
      </body>
    </html>
  );
}
